version: 2

jobs:
  build:
    docker:
      - image: swift
    steps:
      - checkout
      - run:
          name: Install Chromium
          command: git -v
      - run: 
          name: Test code
          command: swift test
     
